/**
 * Side-effect entry point: registers every element under its `ds-*` tag.
 * Safe to import more than once (guards against re-definition).
 */
import { DsAlertDialog } from "./alert-dialog/ds-alert-dialog";
import { DsAvatar } from "./avatar/ds-avatar";
import { DsAvatarGroup } from "./avatar-group/ds-avatar-group";
import { DsBreadcrumb } from "./breadcrumb/ds-breadcrumb";
import { DsButton } from "./button/ds-button";
import { DsButtonGroup } from "./button-group/ds-button-group";
import { DsCard } from "./card/ds-card";
import { DsCheckboxGroup } from "./checkbox-group/ds-checkbox-group";
import { DsCheckbox } from "./checkbox/ds-checkbox";
import { DsCombobox } from "./combobox/ds-combobox";
import { DsConfirmDialog } from "./confirm-dialog/ds-confirm-dialog";
import { DsCount } from "./count/ds-count";
import { DsMultiSelect } from "./multi-select/ds-multi-select";
import { DsNavigationMenu } from "./navigation-menu/ds-navigation-menu";
import { DsPagination } from "./pagination/ds-pagination";
import { DsDialog } from "./dialog/ds-dialog";
import { DsDropdownMenu } from "./dropdown-menu/ds-dropdown-menu";
import { DsEmptyState } from "./empty-state/ds-empty-state";
import { DsErrorState } from "./error-state/ds-error-state";
import { DsInlineNotification } from "./inline-notification/ds-inline-notification";
import { DsLoading } from "./loading/ds-loading";
import { DsLocaleProvider } from "./locale-provider/ds-locale-provider";
import { DsLoadingGenerationArea } from "./loading-generation-area/ds-loading-generation-area";
import { DsField } from "./field/ds-field";
import { DsIcon } from "./icon/ds-icon";
import { DsKbd } from "./kbd/ds-kbd";
import { DsLabel } from "./label/ds-label";
import { DsPromptDialog } from "./prompt-dialog/ds-prompt-dialog";
import { DsRadio } from "./radio/ds-radio";
import { DsRadioGroup } from "./radio-group/ds-radio-group";
import { DsSegmentedControl } from "./segmented-control/ds-segmented-control";
import { DsLink } from "./link/ds-link";
import { DsProgress } from "./progress/ds-progress";
import { DsScrollArea } from "./scroll-area/ds-scroll-area";
import { DsSelect } from "./select/ds-select";
import { DsSeparator } from "./separator/ds-separator";
import { DsTextField, DsTextarea } from "./text-field/ds-text-field";
import { DsSearchDialog } from "./search-dialog/ds-search-dialog";
import { DsSearchField } from "./search-field/ds-search-field";
import { DsSheetDialog } from "./sheet-dialog/ds-sheet-dialog";
import { DsSwitch } from "./switch/ds-switch";
import { DsTable } from "./table/ds-table";
import { DsTableSet } from "./table/ds-table-set";
import { DsTableView } from "./table/ds-table-view";
import { DsSidebar } from "./sidebar/ds-sidebar";
import { DsTab, DsTabList, DsTabPanel } from "./tabs/tab-parts";
import { DsTabs } from "./tabs/ds-tabs";
import { DsTooltip } from "./tooltip/ds-tooltip";
import { DsTag } from "./tag/ds-tag";
import { DsToggleButton } from "./toggle-button/ds-toggle-button";
import { DsToggleGroup } from "./toggle-group/ds-toggle-group";
import { DsTreeView } from "./tree-view/ds-tree-view";
import { DsToolbar } from "./toolbar/ds-toolbar";
import { DsUploadDropArea } from "./upload-drop-area/ds-upload-drop-area";
import { DsLoginForm } from "./login-form/ds-login-form";

const define = (tag: string, ctor: CustomElementConstructor) => {
  if (typeof customElements === "undefined") return;
  if (!customElements.get(tag)) customElements.define(tag, ctor);
};

// First, so a page's existing providers carry `lang` and `dir` before the
// elements inside them render.
define("ds-locale-provider", DsLocaleProvider);
define("ds-button", DsButton);
define("ds-card", DsCard);
define("ds-checkbox", DsCheckbox);
define("ds-switch", DsSwitch);
define("ds-select", DsSelect);
define("ds-separator", DsSeparator);
define("ds-combobox", DsCombobox);
define("ds-multi-select", DsMultiSelect);
define("ds-dialog", DsDialog);
define("ds-alert-dialog", DsAlertDialog);
define("ds-confirm-dialog", DsConfirmDialog);
define("ds-prompt-dialog", DsPromptDialog);
define("ds-search-dialog", DsSearchDialog);
define("ds-dropdown-menu", DsDropdownMenu);
define("ds-empty-state", DsEmptyState);
define("ds-error-state", DsErrorState);
define("ds-inline-notification", DsInlineNotification);
define("ds-loading", DsLoading);
define("ds-loading-generation-area", DsLoadingGenerationArea);
define("ds-label", DsLabel);
define("ds-field", DsField);
define("ds-text-field", DsTextField);
define("ds-textarea", DsTextarea);
define("ds-search-field", DsSearchField);
define("ds-sheet-dialog", DsSheetDialog);
define("ds-radio", DsRadio);
define("ds-radio-group", DsRadioGroup);
define("ds-segmented-control", DsSegmentedControl);
define("ds-checkbox-group", DsCheckboxGroup);
define("ds-table", DsTable);
define("ds-table-view", DsTableView);
define("ds-table-set", DsTableSet);
define("ds-count", DsCount);
define("ds-tabs", DsTabs);
define("ds-avatar", DsAvatar);
define("ds-sidebar", DsSidebar);
define("ds-tooltip", DsTooltip);
define("ds-navigation-menu", DsNavigationMenu);
define("ds-tab-list", DsTabList);
define("ds-tab", DsTab);
define("ds-tab-panel", DsTabPanel);
define("ds-pagination", DsPagination);
define("ds-tag", DsTag);
define("ds-toggle-button", DsToggleButton);
define("ds-toggle-group", DsToggleGroup);
define("ds-tree-view", DsTreeView);
define("ds-toolbar", DsToolbar);
define("ds-upload-drop-area", DsUploadDropArea);
define("ds-login-form", DsLoginForm);
define("ds-button-group", DsButtonGroup);
define("ds-icon", DsIcon);
define("ds-kbd", DsKbd);
define("ds-link", DsLink);
define("ds-avatar-group", DsAvatarGroup);
define("ds-breadcrumb", DsBreadcrumb);
define("ds-progress", DsProgress);
define("ds-scroll-area", DsScrollArea);

export {};
