import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

/// The names, digits, date patterns and hour cycle a locale writes dates
/// and times with, in the Gregorian calendar.
///
/// [DateSymbols.forLocale] returns the CLDR data the web adapters read
/// through `Intl.DateTimeFormat`, for the locales in its table. The shared
/// test vectors in `core/src/calendar/__vectors__/calendar-names.json` hold
/// the same table, and the core tests check it against the runtime's Intl
/// data. Pass explicit symbols for any other locale.
///
/// A pattern is literal text with tokens: `{EEEE}` the long weekday name,
/// `{d}` and `{dd}` the day, `{M}` and `{MM}` the month number, `{MMMM}`
/// the month name from the pattern's own list, and `{y}` the year, each
/// number written in [digits]. Names come from the date's year, month and
/// day alone, so the device's time zone never shifts them.
@immutable
class DateSymbols {
  /// Creates a set of date symbols.
  const DateSymbols({
    required this.weekdays,
    required this.shortWeekdays,
    required this.narrowWeekdays,
    required this.dayPattern,
    required this.dayMonths,
    required this.titlePattern,
    required this.titleMonths,
    required this.mediumPattern,
    required this.mediumMonths,
    required this.hourCycle,
    this.digits = '0123456789',
  }) : assert(digits.length == 10, 'Ten digits, 0 to 9.'),
       assert(hourCycle == 12 || hourCycle == 24, 'A 12- or 24-hour cycle.');

  /// The long weekday names, from Sunday.
  final List<String> weekdays;

  /// The short weekday names, from Sunday: the grid's column headers.
  final List<String> shortWeekdays;

  /// The narrow weekday names, from Sunday.
  final List<String> narrowWeekdays;

  /// A day's full name, its accessible name in a calendar.
  final String dayPattern;

  /// The month names [dayPattern] uses, from January; null when it writes
  /// the month as a number.
  final List<String>? dayMonths;

  /// A month's title, above its grid.
  final String titlePattern;

  /// The month names [titlePattern] uses, from January; null when it
  /// writes the month as a number.
  final List<String>? titleMonths;

  /// A date in a picker field: `Intl`'s medium date style.
  final String mediumPattern;

  /// The month names [mediumPattern] uses, from January; null when it
  /// writes the month as a number.
  final List<String>? mediumMonths;

  /// The hour cycle the locale prefers: 12 or 24.
  final int hourCycle;

  /// The ten digits, 0 to 9, of the locale's numbering system.
  final String digits;

  /// The full name of [date]: `Monday, June 1, 2026`.
  String formatDay(DateTime date) => _format(dayPattern, dayMonths, date);

  /// The title of [date]'s month: `June 2026`.
  String formatMonth(DateTime date) => _format(titlePattern, titleMonths, date);

  /// [date] as a picker field shows it: `Jun 1, 2026`.
  String formatMedium(DateTime date) =>
      _format(mediumPattern, mediumMonths, date);

  /// [value] in the locale's digits, padded to [width].
  String formatNumber(int value, [int width = 1]) {
    final text = value.toString().padLeft(width, '0');
    if (digits == '0123456789') return text;
    return String.fromCharCodes(
      text.codeUnits.map((unit) => digits.codeUnitAt(unit - 0x30)),
    );
  }

  String _format(String pattern, List<String>? months, DateTime date) =>
      pattern.replaceAllMapped(
        _token,
        (match) => switch (match.group(1)) {
          'EEEE' => weekdays[date.weekday % 7],
          'dd' => formatNumber(date.day, 2),
          'd' => formatNumber(date.day),
          'MMMM' => months![date.month - 1],
          'MM' => formatNumber(date.month, 2),
          'M' => formatNumber(date.month),
          _ => formatNumber(date.year),
        },
      );

  static final RegExp _token = RegExp(r'\{(EEEE|dd|d|MMMM|MM|M|y)\}');

  // Generated from Intl data with the Gregorian calendar; the shared vectors
  // hold the same table.
  static const Map<String, DateSymbols> _table = {
    'en': DateSymbols(
      weekdays: [
        'Sunday',
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
      ],
      shortWeekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
      narrowWeekdays: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
      dayPattern: '{EEEE}, {MMMM} {d}, {y}',
      dayMonths: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ],
      mediumPattern: '{MMMM} {d}, {y}',
      mediumMonths: [
        'Jan',
        'Feb',
        'Mar',
        'Apr',
        'May',
        'Jun',
        'Jul',
        'Aug',
        'Sep',
        'Oct',
        'Nov',
        'Dec',
      ],
      hourCycle: 12,
    ),
    'it': DateSymbols(
      weekdays: [
        'domenica',
        'lunedì',
        'martedì',
        'mercoledì',
        'giovedì',
        'venerdì',
        'sabato',
      ],
      shortWeekdays: ['dom', 'lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
      narrowWeekdays: ['D', 'L', 'M', 'M', 'G', 'V', 'S'],
      dayPattern: '{EEEE} {d} {MMMM} {y}',
      dayMonths: [
        'gennaio',
        'febbraio',
        'marzo',
        'aprile',
        'maggio',
        'giugno',
        'luglio',
        'agosto',
        'settembre',
        'ottobre',
        'novembre',
        'dicembre',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'gennaio',
        'febbraio',
        'marzo',
        'aprile',
        'maggio',
        'giugno',
        'luglio',
        'agosto',
        'settembre',
        'ottobre',
        'novembre',
        'dicembre',
      ],
      mediumPattern: '{d} {MMMM} {y}',
      mediumMonths: [
        'gen',
        'feb',
        'mar',
        'apr',
        'mag',
        'giu',
        'lug',
        'ago',
        'set',
        'ott',
        'nov',
        'dic',
      ],
      hourCycle: 24,
    ),
    'de': DateSymbols(
      weekdays: [
        'Sonntag',
        'Montag',
        'Dienstag',
        'Mittwoch',
        'Donnerstag',
        'Freitag',
        'Samstag',
      ],
      shortWeekdays: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
      narrowWeekdays: ['S', 'M', 'D', 'M', 'D', 'F', 'S'],
      dayPattern: '{EEEE}, {d}. {MMMM} {y}',
      dayMonths: [
        'Januar',
        'Februar',
        'März',
        'April',
        'Mai',
        'Juni',
        'Juli',
        'August',
        'September',
        'Oktober',
        'November',
        'Dezember',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'Januar',
        'Februar',
        'März',
        'April',
        'Mai',
        'Juni',
        'Juli',
        'August',
        'September',
        'Oktober',
        'November',
        'Dezember',
      ],
      mediumPattern: '{dd}.{MM}.{y}',
      mediumMonths: null,
      hourCycle: 24,
    ),
    'de-CH': DateSymbols(
      weekdays: [
        'Sonntag',
        'Montag',
        'Dienstag',
        'Mittwoch',
        'Donnerstag',
        'Freitag',
        'Samstag',
      ],
      shortWeekdays: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
      narrowWeekdays: ['S', 'M', 'D', 'M', 'D', 'F', 'S'],
      dayPattern: '{EEEE}, {d}. {MMMM} {y}',
      dayMonths: [
        'Januar',
        'Februar',
        'März',
        'April',
        'Mai',
        'Juni',
        'Juli',
        'August',
        'September',
        'Oktober',
        'November',
        'Dezember',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'Januar',
        'Februar',
        'März',
        'April',
        'Mai',
        'Juni',
        'Juli',
        'August',
        'September',
        'Oktober',
        'November',
        'Dezember',
      ],
      mediumPattern: '{dd}.{MM}.{y}',
      mediumMonths: null,
      hourCycle: 24,
    ),
    'fr': DateSymbols(
      weekdays: [
        'dimanche',
        'lundi',
        'mardi',
        'mercredi',
        'jeudi',
        'vendredi',
        'samedi',
      ],
      shortWeekdays: ['dim.', 'lun.', 'mar.', 'mer.', 'jeu.', 'ven.', 'sam.'],
      narrowWeekdays: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
      dayPattern: '{EEEE} {d} {MMMM} {y}',
      dayMonths: [
        'janvier',
        'février',
        'mars',
        'avril',
        'mai',
        'juin',
        'juillet',
        'août',
        'septembre',
        'octobre',
        'novembre',
        'décembre',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'janvier',
        'février',
        'mars',
        'avril',
        'mai',
        'juin',
        'juillet',
        'août',
        'septembre',
        'octobre',
        'novembre',
        'décembre',
      ],
      mediumPattern: '{d} {MMMM} {y}',
      mediumMonths: [
        'janv.',
        'févr.',
        'mars',
        'avr.',
        'mai',
        'juin',
        'juil.',
        'août',
        'sept.',
        'oct.',
        'nov.',
        'déc.',
      ],
      hourCycle: 24,
    ),
    'fr-CA': DateSymbols(
      weekdays: [
        'dimanche',
        'lundi',
        'mardi',
        'mercredi',
        'jeudi',
        'vendredi',
        'samedi',
      ],
      shortWeekdays: ['dim.', 'lun.', 'mar.', 'mer.', 'jeu.', 'ven.', 'sam.'],
      narrowWeekdays: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
      dayPattern: '{EEEE} {d} {MMMM} {y}',
      dayMonths: [
        'janvier',
        'février',
        'mars',
        'avril',
        'mai',
        'juin',
        'juillet',
        'août',
        'septembre',
        'octobre',
        'novembre',
        'décembre',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'janvier',
        'février',
        'mars',
        'avril',
        'mai',
        'juin',
        'juillet',
        'août',
        'septembre',
        'octobre',
        'novembre',
        'décembre',
      ],
      mediumPattern: '{d} {MMMM} {y}',
      mediumMonths: [
        'janv.',
        'févr.',
        'mars',
        'avr.',
        'mai',
        'juin',
        'juill.',
        'août',
        'sept.',
        'oct.',
        'nov.',
        'déc.',
      ],
      hourCycle: 24,
    ),
    'es': DateSymbols(
      weekdays: [
        'domingo',
        'lunes',
        'martes',
        'miércoles',
        'jueves',
        'viernes',
        'sábado',
      ],
      shortWeekdays: ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'],
      narrowWeekdays: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
      dayPattern: '{EEEE}, {d} de {MMMM} de {y}',
      dayMonths: [
        'enero',
        'febrero',
        'marzo',
        'abril',
        'mayo',
        'junio',
        'julio',
        'agosto',
        'septiembre',
        'octubre',
        'noviembre',
        'diciembre',
      ],
      titlePattern: '{MMMM} de {y}',
      titleMonths: [
        'enero',
        'febrero',
        'marzo',
        'abril',
        'mayo',
        'junio',
        'julio',
        'agosto',
        'septiembre',
        'octubre',
        'noviembre',
        'diciembre',
      ],
      mediumPattern: '{d} {MMMM} {y}',
      mediumMonths: [
        'ene',
        'feb',
        'mar',
        'abr',
        'may',
        'jun',
        'jul',
        'ago',
        'sept',
        'oct',
        'nov',
        'dic',
      ],
      hourCycle: 24,
    ),
    'es-MX': DateSymbols(
      weekdays: [
        'domingo',
        'lunes',
        'martes',
        'miércoles',
        'jueves',
        'viernes',
        'sábado',
      ],
      shortWeekdays: ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'],
      narrowWeekdays: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
      dayPattern: '{EEEE}, {d} de {MMMM} de {y}',
      dayMonths: [
        'enero',
        'febrero',
        'marzo',
        'abril',
        'mayo',
        'junio',
        'julio',
        'agosto',
        'septiembre',
        'octubre',
        'noviembre',
        'diciembre',
      ],
      titlePattern: '{MMMM} de {y}',
      titleMonths: [
        'enero',
        'febrero',
        'marzo',
        'abril',
        'mayo',
        'junio',
        'julio',
        'agosto',
        'septiembre',
        'octubre',
        'noviembre',
        'diciembre',
      ],
      mediumPattern: '{d} {MMMM} {y}',
      mediumMonths: [
        'ene',
        'feb',
        'mar',
        'abr',
        'may',
        'jun',
        'jul',
        'ago',
        'sep',
        'oct',
        'nov',
        'dic',
      ],
      hourCycle: 12,
    ),
    'pt': DateSymbols(
      weekdays: [
        'domingo',
        'segunda-feira',
        'terça-feira',
        'quarta-feira',
        'quinta-feira',
        'sexta-feira',
        'sábado',
      ],
      shortWeekdays: ['dom.', 'seg.', 'ter.', 'qua.', 'qui.', 'sex.', 'sáb.'],
      narrowWeekdays: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
      dayPattern: '{EEEE}, {d} de {MMMM} de {y}',
      dayMonths: [
        'janeiro',
        'fevereiro',
        'março',
        'abril',
        'maio',
        'junho',
        'julho',
        'agosto',
        'setembro',
        'outubro',
        'novembro',
        'dezembro',
      ],
      titlePattern: '{MMMM} de {y}',
      titleMonths: [
        'janeiro',
        'fevereiro',
        'março',
        'abril',
        'maio',
        'junho',
        'julho',
        'agosto',
        'setembro',
        'outubro',
        'novembro',
        'dezembro',
      ],
      mediumPattern: '{d} de {MMMM} de {y}',
      mediumMonths: [
        'jan.',
        'fev.',
        'mar.',
        'abr.',
        'mai.',
        'jun.',
        'jul.',
        'ago.',
        'set.',
        'out.',
        'nov.',
        'dez.',
      ],
      hourCycle: 24,
    ),
    'pt-PT': DateSymbols(
      weekdays: [
        'domingo',
        'segunda-feira',
        'terça-feira',
        'quarta-feira',
        'quinta-feira',
        'sexta-feira',
        'sábado',
      ],
      shortWeekdays: [
        'domingo',
        'segunda',
        'terça',
        'quarta',
        'quinta',
        'sexta',
        'sábado',
      ],
      narrowWeekdays: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
      dayPattern: '{EEEE}, {d} de {MMMM} de {y}',
      dayMonths: [
        'janeiro',
        'fevereiro',
        'março',
        'abril',
        'maio',
        'junho',
        'julho',
        'agosto',
        'setembro',
        'outubro',
        'novembro',
        'dezembro',
      ],
      titlePattern: '{MMMM} de {y}',
      titleMonths: [
        'janeiro',
        'fevereiro',
        'março',
        'abril',
        'maio',
        'junho',
        'julho',
        'agosto',
        'setembro',
        'outubro',
        'novembro',
        'dezembro',
      ],
      mediumPattern: '{dd}/{MM}/{y}',
      mediumMonths: null,
      hourCycle: 24,
    ),
    'nl': DateSymbols(
      weekdays: [
        'zondag',
        'maandag',
        'dinsdag',
        'woensdag',
        'donderdag',
        'vrijdag',
        'zaterdag',
      ],
      shortWeekdays: ['zo', 'ma', 'di', 'wo', 'do', 'vr', 'za'],
      narrowWeekdays: ['Z', 'M', 'D', 'W', 'D', 'V', 'Z'],
      dayPattern: '{EEEE} {d} {MMMM} {y}',
      dayMonths: [
        'januari',
        'februari',
        'maart',
        'april',
        'mei',
        'juni',
        'juli',
        'augustus',
        'september',
        'oktober',
        'november',
        'december',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'januari',
        'februari',
        'maart',
        'april',
        'mei',
        'juni',
        'juli',
        'augustus',
        'september',
        'oktober',
        'november',
        'december',
      ],
      mediumPattern: '{d} {MMMM} {y}',
      mediumMonths: [
        'jan',
        'feb',
        'mrt',
        'apr',
        'mei',
        'jun',
        'jul',
        'aug',
        'sep',
        'okt',
        'nov',
        'dec',
      ],
      hourCycle: 24,
    ),
    'pl': DateSymbols(
      weekdays: [
        'niedziela',
        'poniedziałek',
        'wtorek',
        'środa',
        'czwartek',
        'piątek',
        'sobota',
      ],
      shortWeekdays: ['niedz.', 'pon.', 'wt.', 'śr.', 'czw.', 'pt.', 'sob.'],
      narrowWeekdays: ['N', 'P', 'W', 'Ś', 'C', 'P', 'S'],
      dayPattern: '{EEEE}, {d} {MMMM} {y}',
      dayMonths: [
        'stycznia',
        'lutego',
        'marca',
        'kwietnia',
        'maja',
        'czerwca',
        'lipca',
        'sierpnia',
        'września',
        'października',
        'listopada',
        'grudnia',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'styczeń',
        'luty',
        'marzec',
        'kwiecień',
        'maj',
        'czerwiec',
        'lipiec',
        'sierpień',
        'wrzesień',
        'październik',
        'listopad',
        'grudzień',
      ],
      mediumPattern: '{d} {MMMM} {y}',
      mediumMonths: [
        'sty',
        'lut',
        'mar',
        'kwi',
        'maj',
        'cze',
        'lip',
        'sie',
        'wrz',
        'paź',
        'lis',
        'gru',
      ],
      hourCycle: 24,
    ),
    'sv': DateSymbols(
      weekdays: [
        'söndag',
        'måndag',
        'tisdag',
        'onsdag',
        'torsdag',
        'fredag',
        'lördag',
      ],
      shortWeekdays: ['sön', 'mån', 'tis', 'ons', 'tors', 'fre', 'lör'],
      narrowWeekdays: ['S', 'M', 'T', 'O', 'T', 'F', 'L'],
      dayPattern: '{EEEE} {d} {MMMM} {y}',
      dayMonths: [
        'januari',
        'februari',
        'mars',
        'april',
        'maj',
        'juni',
        'juli',
        'augusti',
        'september',
        'oktober',
        'november',
        'december',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'januari',
        'februari',
        'mars',
        'april',
        'maj',
        'juni',
        'juli',
        'augusti',
        'september',
        'oktober',
        'november',
        'december',
      ],
      mediumPattern: '{d} {MMMM} {y}',
      mediumMonths: [
        'jan.',
        'feb.',
        'mars',
        'apr.',
        'maj',
        'juni',
        'juli',
        'aug.',
        'sep.',
        'okt.',
        'nov.',
        'dec.',
      ],
      hourCycle: 24,
    ),
    'ru': DateSymbols(
      weekdays: [
        'воскресенье',
        'понедельник',
        'вторник',
        'среда',
        'четверг',
        'пятница',
        'суббота',
      ],
      shortWeekdays: ['вс', 'пн', 'вт', 'ср', 'чт', 'пт', 'сб'],
      narrowWeekdays: ['В', 'П', 'В', 'С', 'Ч', 'П', 'С'],
      dayPattern: '{EEEE}, {d} {MMMM} {y} г.',
      dayMonths: [
        'января',
        'февраля',
        'марта',
        'апреля',
        'мая',
        'июня',
        'июля',
        'августа',
        'сентября',
        'октября',
        'ноября',
        'декабря',
      ],
      titlePattern: '{MMMM} {y} г.',
      titleMonths: [
        'январь',
        'февраль',
        'март',
        'апрель',
        'май',
        'июнь',
        'июль',
        'август',
        'сентябрь',
        'октябрь',
        'ноябрь',
        'декабрь',
      ],
      mediumPattern: '{d} {MMMM} {y} г.',
      mediumMonths: [
        'янв.',
        'февр.',
        'мар.',
        'апр.',
        'мая',
        'июн.',
        'июл.',
        'авг.',
        'сент.',
        'окт.',
        'нояб.',
        'дек.',
      ],
      hourCycle: 24,
    ),
    'tr': DateSymbols(
      weekdays: [
        'Pazar',
        'Pazartesi',
        'Salı',
        'Çarşamba',
        'Perşembe',
        'Cuma',
        'Cumartesi',
      ],
      shortWeekdays: ['Paz', 'Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt'],
      narrowWeekdays: ['P', 'P', 'S', 'Ç', 'P', 'C', 'C'],
      dayPattern: '{d} {MMMM} {y} {EEEE}',
      dayMonths: [
        'Ocak',
        'Şubat',
        'Mart',
        'Nisan',
        'Mayıs',
        'Haziran',
        'Temmuz',
        'Ağustos',
        'Eylül',
        'Ekim',
        'Kasım',
        'Aralık',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'Ocak',
        'Şubat',
        'Mart',
        'Nisan',
        'Mayıs',
        'Haziran',
        'Temmuz',
        'Ağustos',
        'Eylül',
        'Ekim',
        'Kasım',
        'Aralık',
      ],
      mediumPattern: '{d} {MMMM} {y}',
      mediumMonths: [
        'Oca',
        'Şub',
        'Mar',
        'Nis',
        'May',
        'Haz',
        'Tem',
        'Ağu',
        'Eyl',
        'Eki',
        'Kas',
        'Ara',
      ],
      hourCycle: 24,
    ),
    'ja': DateSymbols(
      weekdays: ['日曜日', '月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日'],
      shortWeekdays: ['日', '月', '火', '水', '木', '金', '土'],
      narrowWeekdays: ['日', '月', '火', '水', '木', '金', '土'],
      dayPattern: '{y}年{M}月{d}日{EEEE}',
      dayMonths: null,
      titlePattern: '{y}年{M}月',
      titleMonths: null,
      mediumPattern: '{y}/{MM}/{dd}',
      mediumMonths: null,
      hourCycle: 24,
    ),
    'zh': DateSymbols(
      weekdays: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
      shortWeekdays: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
      narrowWeekdays: ['日', '一', '二', '三', '四', '五', '六'],
      dayPattern: '{y}年{M}月{d}日{EEEE}',
      dayMonths: null,
      titlePattern: '{y}年{M}月',
      titleMonths: null,
      mediumPattern: '{y}年{M}月{d}日',
      mediumMonths: null,
      hourCycle: 24,
    ),
    'ar': DateSymbols(
      weekdays: [
        'الأحد',
        'الاثنين',
        'الثلاثاء',
        'الأربعاء',
        'الخميس',
        'الجمعة',
        'السبت',
      ],
      shortWeekdays: [
        'الأحد',
        'الاثنين',
        'الثلاثاء',
        'الأربعاء',
        'الخميس',
        'الجمعة',
        'السبت',
      ],
      narrowWeekdays: ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'],
      dayPattern: '{EEEE}، {d} {MMMM} {y}',
      dayMonths: [
        'يناير',
        'فبراير',
        'مارس',
        'أبريل',
        'مايو',
        'يونيو',
        'يوليو',
        'أغسطس',
        'سبتمبر',
        'أكتوبر',
        'نوفمبر',
        'ديسمبر',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'يناير',
        'فبراير',
        'مارس',
        'أبريل',
        'مايو',
        'يونيو',
        'يوليو',
        'أغسطس',
        'سبتمبر',
        'أكتوبر',
        'نوفمبر',
        'ديسمبر',
      ],
      mediumPattern: '{dd}\u200f/{MM}\u200f/{y}',
      mediumMonths: null,
      hourCycle: 12,
    ),
    'ar-EG': DateSymbols(
      weekdays: [
        'الأحد',
        'الاثنين',
        'الثلاثاء',
        'الأربعاء',
        'الخميس',
        'الجمعة',
        'السبت',
      ],
      shortWeekdays: [
        'الأحد',
        'الاثنين',
        'الثلاثاء',
        'الأربعاء',
        'الخميس',
        'الجمعة',
        'السبت',
      ],
      narrowWeekdays: ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'],
      dayPattern: '{EEEE}، {d} {MMMM} {y}',
      dayMonths: [
        'يناير',
        'فبراير',
        'مارس',
        'أبريل',
        'مايو',
        'يونيو',
        'يوليو',
        'أغسطس',
        'سبتمبر',
        'أكتوبر',
        'نوفمبر',
        'ديسمبر',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'يناير',
        'فبراير',
        'مارس',
        'أبريل',
        'مايو',
        'يونيو',
        'يوليو',
        'أغسطس',
        'سبتمبر',
        'أكتوبر',
        'نوفمبر',
        'ديسمبر',
      ],
      mediumPattern: '{dd}\u200f/{MM}\u200f/{y}',
      mediumMonths: null,
      digits: '٠١٢٣٤٥٦٧٨٩',
      hourCycle: 12,
    ),
    'ar-SA': DateSymbols(
      weekdays: [
        'الأحد',
        'الاثنين',
        'الثلاثاء',
        'الأربعاء',
        'الخميس',
        'الجمعة',
        'السبت',
      ],
      shortWeekdays: [
        'الأحد',
        'الاثنين',
        'الثلاثاء',
        'الأربعاء',
        'الخميس',
        'الجمعة',
        'السبت',
      ],
      narrowWeekdays: ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'],
      dayPattern: '{EEEE}، {d} {MMMM} {y}',
      dayMonths: [
        'يناير',
        'فبراير',
        'مارس',
        'أبريل',
        'مايو',
        'يونيو',
        'يوليو',
        'أغسطس',
        'سبتمبر',
        'أكتوبر',
        'نوفمبر',
        'ديسمبر',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'يناير',
        'فبراير',
        'مارس',
        'أبريل',
        'مايو',
        'يونيو',
        'يوليو',
        'أغسطس',
        'سبتمبر',
        'أكتوبر',
        'نوفمبر',
        'ديسمبر',
      ],
      mediumPattern: '{dd}\u200f/{MM}\u200f/{y}',
      mediumMonths: null,
      digits: '٠١٢٣٤٥٦٧٨٩',
      hourCycle: 12,
    ),
    'ar-MA': DateSymbols(
      weekdays: [
        'الأحد',
        'الاثنين',
        'الثلاثاء',
        'الأربعاء',
        'الخميس',
        'الجمعة',
        'السبت',
      ],
      shortWeekdays: [
        'الأحد',
        'الاثنين',
        'الثلاثاء',
        'الأربعاء',
        'الخميس',
        'الجمعة',
        'السبت',
      ],
      narrowWeekdays: ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'],
      dayPattern: '{EEEE}، {d} {MMMM} {y}',
      dayMonths: [
        'يناير',
        'فبراير',
        'مارس',
        'أبريل',
        'ماي',
        'يونيو',
        'يوليوز',
        'غشت',
        'شتنبر',
        'أكتوبر',
        'نونبر',
        'دجنبر',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'يناير',
        'فبراير',
        'مارس',
        'أبريل',
        'ماي',
        'يونيو',
        'يوليوز',
        'غشت',
        'شتنبر',
        'أكتوبر',
        'نونبر',
        'دجنبر',
      ],
      mediumPattern: '{dd}\u200f/{MM}\u200f/{y}',
      mediumMonths: null,
      hourCycle: 24,
    ),
    'he': DateSymbols(
      weekdays: [
        'יום ראשון',
        'יום שני',
        'יום שלישי',
        'יום רביעי',
        'יום חמישי',
        'יום שישי',
        'יום שבת',
      ],
      shortWeekdays: [
        'יום א׳',
        'יום ב׳',
        'יום ג׳',
        'יום ד׳',
        'יום ה׳',
        'יום ו׳',
        'שבת',
      ],
      narrowWeekdays: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ש׳'],
      dayPattern: '{EEEE}, {d} ב{MMMM} {y}',
      dayMonths: [
        'ינואר',
        'פברואר',
        'מרץ',
        'אפריל',
        'מאי',
        'יוני',
        'יולי',
        'אוגוסט',
        'ספטמבר',
        'אוקטובר',
        'נובמבר',
        'דצמבר',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'ינואר',
        'פברואר',
        'מרץ',
        'אפריל',
        'מאי',
        'יוני',
        'יולי',
        'אוגוסט',
        'ספטמבר',
        'אוקטובר',
        'נובמבר',
        'דצמבר',
      ],
      mediumPattern: '{d} ב{MMMM} {y}',
      mediumMonths: [
        'ינו׳',
        'פבר׳',
        'מרץ',
        'אפר׳',
        'מאי',
        'יוני',
        'יולי',
        'אוג׳',
        'ספט׳',
        'אוק׳',
        'נוב׳',
        'דצמ׳',
      ],
      hourCycle: 24,
    ),
    'fa': DateSymbols(
      weekdays: [
        'یکشنبه',
        'دوشنبه',
        'سه‌شنبه',
        'چهارشنبه',
        'پنجشنبه',
        'جمعه',
        'شنبه',
      ],
      shortWeekdays: [
        'یکشنبه',
        'دوشنبه',
        'سه‌شنبه',
        'چهارشنبه',
        'پنجشنبه',
        'جمعه',
        'شنبه',
      ],
      narrowWeekdays: ['ی', 'د', 'س', 'چ', 'پ', 'ج', 'ش'],
      dayPattern: '{EEEE} {d} {MMMM} {y}',
      dayMonths: [
        'ژانویهٔ',
        'فوریهٔ',
        'مارس',
        'آوریل',
        'مهٔ',
        'ژوئن',
        'ژوئیهٔ',
        'اوت',
        'سپتامبر',
        'اکتبر',
        'نوامبر',
        'دسامبر',
      ],
      titlePattern: '{MMMM} {y}',
      titleMonths: [
        'ژانویهٔ',
        'فوریهٔ',
        'مارس',
        'آوریل',
        'مهٔ',
        'ژوئن',
        'ژوئیهٔ',
        'اوت',
        'سپتامبر',
        'اکتبر',
        'نوامبر',
        'دسامبر',
      ],
      mediumPattern: '{d} {MMMM} {y}',
      mediumMonths: [
        'ژانویه',
        'فوریه',
        'مارس',
        'آوریل',
        'مه',
        'ژوئن',
        'ژوئیه',
        'اوت',
        'سپتامبر',
        'اکتبر',
        'نوامبر',
        'دسامبر',
      ],
      digits: '۰۱۲۳۴۵۶۷۸۹',
      hourCycle: 24,
    ),
  };

  /// The symbols a widget uses: [symbols] when given, else those of
  /// [locale], else of the app's locale from [Localizations], else English.
  static DateSymbols resolve(
    BuildContext context, {
    Locale? locale,
    DateSymbols? symbols,
  }) =>
      symbols ??
      forLocale(
        locale ?? Localizations.maybeLocaleOf(context) ?? const Locale('en'),
      );

  /// English, the fallback for a locale missing from the table.
  static DateSymbols get english => _table['en']!;

  /// The symbols of [locale]: its language and country, then its language
  /// alone, then English.
  static DateSymbols forLocale(Locale locale) {
    final country = locale.countryCode;
    return (country == null
            ? null
            : _table['${locale.languageCode}-$country']) ??
        _table[locale.languageCode] ??
        english;
  }

  @override
  bool operator ==(Object other) =>
      other is DateSymbols &&
      listEquals(other.weekdays, weekdays) &&
      listEquals(other.shortWeekdays, shortWeekdays) &&
      listEquals(other.narrowWeekdays, narrowWeekdays) &&
      other.dayPattern == dayPattern &&
      listEquals(other.dayMonths, dayMonths) &&
      other.titlePattern == titlePattern &&
      listEquals(other.titleMonths, titleMonths) &&
      other.mediumPattern == mediumPattern &&
      listEquals(other.mediumMonths, mediumMonths) &&
      other.hourCycle == hourCycle &&
      other.digits == digits;

  @override
  int get hashCode => Object.hash(
    Object.hashAll(weekdays),
    dayPattern,
    titlePattern,
    mediumPattern,
    hourCycle,
    digits,
  );
}
